site_name: confu
site_url: https://github.com/20c/confu

theme: readthedocs

pages:
  - Home: index.md
  - Quickstart: quickstart.md
  - CLI: cli.md

markdown_extensions:
  - markdown_include.include
