# Generated by Django 2.2.12 on 2020-05-19 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_id', models.PositiveIntegerField()),
                ('data', models.TextField(default='{}')),
                ('holder_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'db_table': 'confu_config',
                'unique_together': {('holder_content_type', 'holder_id')},
            },
        ),
    ]
